### PR TITLE
SVG versions of illustrations

### PR DESCRIPTION
**Pull request by davidscotson**
SVG generated from PNG scans.

### CODE REVIEW

**Comment by davidscotson** [comment]
These are SVG versions created from the PNG scans.

They should be visually the same, except for 3 and 6 which I had some odd trouble with Inkscape on. ```se lint``` reported issues with transforms, and I couldn't get rid of the transforms without adding a slight border to one, and reducing the size of the other by x2 (though obviously for SVG actual size doesn't really matter as it's vector). Possibly just user error on my part, but the differences don't seem material.

Github doesn't make it easy to view visual diffs when you replace PNGs with equivalent SVGs, simplest workflow I could figure out was to open each image in it's own browser window from the diff and switch between them to compare.

There is one remaining ```se lint``` issue. It complains about the use of an #id in the xml. I believe this is required to add the very small amount of guassian blur filter via an SVG filter that I used to soften the edges of the text.

This effect is so small that it's basically invisible at common e-reader sizes and only really makes a difference if looking at the image full size on e.g. a Retina Macbook, so it could be taken out easily if that lint error is considered a blocker.

The images are generally larger in Kb than the PNG, but I think once you take zipping of xml into account they're generally smaller again.

(I'd previously attempted to SVG-ize these images in Inkscape, and failed miserably. I put that down to a combination of user error and the UI not being great. After some experimentation, the biggest thing was to stop trying to "simplify" the SVG in Inkscape, which consider the entire image as a single "line" and therefore does things that seem very odd to humans. You can break the line apart into seperate parts, and the simplify routine then works magically well on each individual item, creating what a skilled human would create, but to use that then you need to manually put the holes back in individual letters like b p a, which it also breaks apart which isn't really a fun task on some of these images.

Giving up on that process (except for on images like the first that only had large objects) and just using standard web SVG minifiers to reduce the excess information from the complex SVG that Inkscape generates when it traces, on the other hand is a fairly automatic process (that could probably be done as a bash script with no human intervention) and seemed to get to roughly the same eventual size/quality as the hand-crafted approach. There's probably room for further size savings if some tool was smart enough to do the inkscape simplification thing on only certain parts of the image and/or automatically re-attach the insides of hollow shapes, but probably not enough to bother about).

**Comment by davidscotson** [comment]
4,5 and 9 have parts that may have originally been a different color originally, and have been darkened via the various conversions and so some contrast has been lost, I might revisit parts of those, and 6 could probably do with a rescan to get higher resolution, but those are fairly minor things when viewed at typical sizes I think.

**Comment by davidscotson** [comment]
On further investigation, the parts that I thought might have been printed in gray (or stippled in some way to give that effect with monochrome printing press) weren't after all. I think the software that processed the original scans may have had some feature that detected "text" like things, vs "image like things" and processed them differently. With large posters of Cyrillic in a variety of old fashioned typefaces, I think it guesses wrong sometimes, so some parts are aggresively cleaned up, while others are left alone, but the original paper book printing or photographic scans would have had both the same color of ink so having them the same color should be fine.

You can see this most clearly on scan page 126 where the tops of a few letters around the middle go from being treated as text, to being treated as an image, and the contrast changes sharply with the background going from blank white to a noisey gray:

https://babel.hathitrust.org/cgi/pt?id=wu.89048868350&view=1up&seq=126

**Comment by acabal** [comment]
Great work!

Re. filters, I don't think we really need those... They look basically the same on my own hi-dpi screen, and I don't think anybody's going to be zooming in super close for a king-sized view of some text in the general case. We can remove those and that will fix lint as well.

In `./images/`, we want the original source images before modifications or format changes. Right now it's all SVG in there which is the opposite of what we want, we want the images in there to be the raw PNG sources. The distributable SVGs go in `./src/epub/images/`. Right now there are some PNGs in there, even though `./images/` has SVG traces of it looks like all of the illustrations. So `./images/` should be all raw PNG, `./src/epub/images/` should be all final SVG.

Lastly you also run `se clean` on the repo to pretty print the SVGs?

**Comment by acabal** [comment]
Just checking in, are you still working on this?

**Comment by acabal** [comment]
Just wanted to ping you one more time on this to see if you're making progress. I'd hate to lose this PR! :)

**Comment by acabal** [comment]
Closed due to inactivity. If you have time to wrap this up, please feel free to reopen!

**Pull request closed without merging**
