### PR TITLE
[Editorial] minify by removing JPEG artifacts

### PR DESCRIPTION
**Pull request by davidscotson**
I marked this editorial are there are subtle visible changes to the images, as well as the reduction in file size.

The files are between one quarter and one eigth of their previous size, while being effectively identical for the casual viewer.

They are different though, and I think they look better now but that's possibly a matter of opinion, it's not a purely mechanical and lossless improvement by running some PNG optimizers on them, though I did that as well.

The main change was to remove some JPEG fuzziness around the smaller text introduced by conversion by Google/Hathi of what I presume to be TIFF original scans into JPEG for web display, by basically following this procedure:

https://www.youtube.com/watch?v=caQoQgXzPzQ

That tutorial is about removing the background color from a logo, but it does talk about the two extra steps available in this tool that I used, a) getting rid of anything that is almost, but not quite the exact same color as the background, this is what counters the JPEG tendancy to add light gray fuzz around sharp edges like text, b) setting some things that are almost, but not quite fully black, to be 100% black and opaque. I used about 10% on each side, just eyeballing it. The net effect is a sharpening of the text, which I think actually improves the look, and a greater ability for PNG to work it's magic on long solid runs of white pixels. Which reminds me, after running the color to alpha on the white background, I brought a solid white background back. Overally I'd decribe the change as looking like the images have been through the photocopier one or two times less.

### CODE REVIEW

**Comment by davidscotson** [comment]
Forgot to mention one other editorial decision included here.

One of the images was rotated 90 degrees to better match the aspect ratio of the original paper page. This seemed unneccesary for a digital reader that can resize and zoom images at will, so I rotated it back to its natural orientation.

**Comment by acabal** [comment]
Actually, if you want to go even farther, these are all good candidates to be traced into SVG. Any image that is just black on white/transparent can be traced into SVG and with the right semantics will invert for night mode once in the ebook. Inkscape has a function for this that should make the process fairly easy. Can you do that?

**Comment by davidscotson** [comment]
I did actually give that a go first, and I didn't seem to have great success, the smaller text was already nearly shapeless blobs, which made things difficult for the tracing, and I felt the sharp edged tracing lost some of the analog character of the originals.

However, there is a variation in text size, the larger poster type would probably work better than the newsprint sized text. I also tried the very first image, which is one large sentence. It didn't seem like it was much smaller in filesize, but possibly I just didn't tweak the settings enough so I'll give it another go. Though I guess if there were some higher resolution scans available that might work better as input for the SVG tracing algorithm.

**Comment by acabal** [comment]
You know, I must have decided the same thing when I worked on this at first. That would explain why it's currently not in SVG. Let's leave it for now unless you want to work on it and have a breakthrough. Thanks for working on this!

**Pull request merged**
